'use strict';
const $=id=>document.getElementById(id),C=RouletteCore,STORE='roulette-note-v1';
let state={version:1,active:'',lists:{}},view='viewer',demo=false,lastMessage=0,toastTimer;
function toast(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500);}
function validateState(raw){if(!raw||raw.version!==1||!raw.lists||typeof raw.lists!=='object'||Array.isArray(raw.lists)||Object.keys(raw.lists).length>200)throw Error('지원하지 않는 백업 형식입니다.');const out={version:1,active:String(raw.active||''),lists:{}};for(const [id,l]of Object.entries(raw.lists)){if(!/^[a-zA-Z0-9_-]{1,80}$/.test(id)||!l||typeof l.label!=='string'||l.label.length>80)throw Error('백업 목록이 올바르지 않습니다.');const rows=C.taskRows(l.rows);const done={};for(const r of rows){let v=l.done?.[C.keyOf(r)];if(Number.isSafeInteger(v)&&v>=0)done[C.keyOf(r)]=Math.min(v,r.count);}out.lists[id]={label:l.label,rows,done,updated:typeof l.updated==='string'?l.updated:''};}if(!Object.hasOwn(out.lists,out.active))out.active=Object.keys(out.lists)[0]||'';return out;}
try{const saved=localStorage.getItem(STORE);if(saved)state=validateState(JSON.parse(saved));}catch(e){toast('저장된 목록을 읽지 못했습니다. 백업을 불러와 주세요.');}
function save(){if(demo)return;try{localStorage.setItem(STORE,JSON.stringify(state));}catch(e){toast('브라우저 저장 공간이 부족합니다. 백업 저장을 눌러 주세요.');}}
const current=()=>state.lists[state.active]||{label:'',rows:[],done:{},updated:''};
function makeList(label,activate=true){label=label.trim().slice(0,80);if(!label)throw Error('목록 이름을 입력해 주세요.');let entry=Object.entries(state.lists).find(([,v])=>v.label===label);const id=entry?entry[0]:crypto.randomUUID();if(!entry)state.lists[id]={label,rows:[],done:{},updated:''};if(activate)state.active=id;return state.lists[id];}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function render(){const list=current(),s=C.summary(list.rows,list.done);$('datasetSelect').replaceChildren();for(const [id,l]of Object.entries(state.lists)){const o=new Option(l.label,id);$('datasetSelect').add(o);}if(!Object.keys(state.lists).length)$('datasetSelect').add(new Option('목록 없음',''));$('datasetSelect').value=state.active;for(const [id,n,unit] of [['totalCount',s.total,'회'],['viewerCount',s.users,'명'],['remainingCount',s.total-s.completed,'회'],['itemCount',s.items.length,'종']]){$(id).replaceChildren(document.createTextNode(n.toLocaleString()),el('small',unit));}$('doneCaption').textContent='완료 '+s.completed.toLocaleString()+'회';$('byViewer').setAttribute('aria-selected',String(view==='viewer'));$('byItem').setAttribute('aria-selected',String(view==='item'));renderTable();$('distribution').replaceChildren();if(!s.total){$('distribution').append(el('p','연결하면 항목별 비율이 표시됩니다.','help'));}else{for(const [item,count] of s.items){const row=el('div',undefined,'dist-row'),label=el('div',undefined,'dist-label'),track=el('div',undefined,'track'),bar=el('span');label.append(el('span',item),el('span',count+'회 · '+(count/s.total*100).toFixed(1)+'%'));bar.style.width=(count/s.total*100)+'%';track.append(bar);row.append(label,track);$('distribution').append(row);}}$('csvButton').disabled=!list.rows.length;$('backupButton').disabled=demo||!Object.keys(state.lists).length;}
function renderTable(){const list=current(),query=$('searchInput').value.toLocaleLowerCase(),pending=$('pendingOnly').checked;let rows=list.rows.filter(r=>(r.user+' '+r.id+' '+r.item).toLocaleLowerCase().includes(query)&&(!pending||r.count>(list.done[C.keyOf(r)]||0)));rows.sort((a,b)=>view==='viewer'?(a.user.localeCompare(b.user,'ko')||a.id.localeCompare(b.id)||b.count-a.count):(a.item.localeCompare(b.item,'ko')||b.count-a.count));const area=$('tableArea');area.replaceChildren();if(!rows.length){const empty=el('div',undefined,'empty');empty.append(el('span',list.rows.length?'✓':'◴','symbol'),el('h3',list.rows.length?'해당하는 항목이 없습니다':'첫 룰렛 내역을 연결해 보세요'),el('p',list.rows.length?'검색어나 미완료 필터를 확인해 주세요.':'위플랩 통계를 연결하면 자동으로 정리됩니다.'));area.append(empty);return;}const table=el('table'),thead=el('thead'),tr=el('tr');for(const text of [...(view==='viewer'?['후원자','당첨 항목']:['당첨 항목','후원자']),'남음','완료 / 전체']){const th=el('th',text);th.scope='col';tr.append(th);}thead.append(tr);table.append(thead);const groups=new Map();for(const r of rows){const id=view==='viewer'?(r.id||r.user):r.item;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(r);}rows=[...groups.values()].flat();const seen=new Set();const body=el('tbody');for(const r of rows){const row=el('tr'),name=el('td',r.user),item=el('td'),count=el('td',(r.count-Math.min(r.count,list.done[C.keyOf(r)]||0)).toLocaleString(),'remaining'),action=el('td'),counter=el('div',undefined,'counter'),key=C.keyOf(r),done=Math.min(r.count,list.done[key]||0);name.className='viewer-name';name.append(el('span',r.id||'아이디 없음','sub'));const groupId=view==='viewer'?(r.id||r.user):r.item;if(!seen.has(groupId)){const merged=view==='viewer'?name:item;merged.rowSpan=groups.get(groupId).length;merged.classList.add('group-cell');row.className='group-start';row.append(merged);seen.add(groupId);}item.append(el('span',r.item,'badge'));for(const delta of [-1,1]){const b=el('button',delta===-1?'−':'+');b.setAttribute('aria-label',r.user+' '+r.item+' 완료 '+(delta===-1?'취소':'추가'));b.disabled=delta===-1?done<=0:done>=r.count;b.onclick=()=>{list.done[key]=done+delta;save();render();};if(delta===1)counter.append(el('span',done+' / '+r.count,done===r.count?'complete':''));counter.append(b);}action.append(counter);row.append(view==='viewer'?item:name,count,action);body.append(row);}table.append(body);area.append(table,el('div',rows.length+'개 항목 · 완료 표시는 위플랩 원본에 영향을 주지 않습니다.','table-info'));}
function updateBookmark(){const label=$('datasetName').value.trim()||'기본 목록';const target=new URL('.',location.href).href;const code='javascript:'+encodeURIComponent('('+rouletteConnector.toString()+')('+JSON.stringify(target)+','+JSON.stringify(label)+');void 0');$('bookmark').href=code;$('bookmarkCode').value=code;}
$('setupButton').onclick=()=>{$('datasetName').value=current().label||new Date().toLocaleDateString('ko-KR')+' 방송';updateBookmark();$('setupDialog').showModal();};$('datasetName').oninput=updateBookmark;$('closeSetup').onclick=()=>$('setupDialog').close();$('bookmark').onclick=e=>{e.preventDefault();toast('이 버튼을 북마크 바에 드래그한 뒤, 위플랩에서 실행해 주세요.');};$('copyBookmark').onclick=async()=>{try{await navigator.clipboard.writeText($('bookmarkCode').value);toast('북마크 주소를 복사했습니다.');}catch(e){$('bookmarkCode').select();toast('선택된 코드를 복사해 주세요.');}};
$('newButton').onclick=()=>{$('newName').value=new Date().toLocaleDateString('ko-KR')+' 방송';$('nameDialog').showModal();};$('nameDialog').addEventListener('close',()=>{if($('nameDialog').returnValue!=='create')return;exitDemo();try{makeList($('newName').value);save();render();}catch(e){toast(e.message);}});
$('datasetSelect').onchange=()=>{state.active=$('datasetSelect').value;save();render();};$('byViewer').onclick=()=>{view='viewer';render();};$('byItem').onclick=()=>{view='item';render();};$('searchInput').oninput=renderTable;$('pendingOnly').onchange=renderTable;
function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('csvButton').onclick=()=>download(C.csv(current().rows,current().done),'text/csv;charset=utf-8','roulette-summary.csv');$('backupButton').onclick=()=>download(JSON.stringify(state,null,2),'application/json','roulette-backup-'+new Date().toISOString().slice(0,10)+'.json');$('restoreButton').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>10000000)throw Error('10MB 이하의 백업만 불러올 수 있습니다.');const restored=validateState(JSON.parse(await f.text()));exitDemo();for(const l of Object.values(restored.lists)){const id=crypto.randomUUID();state.lists[id]={...l,label:(l.label+' (복원)').slice(0,80)};state.active=id;}save();render();toast('백업을 새 목록으로 불러왔습니다.');}catch(err){toast(err.message);}};
let beforeDemo;function exitDemo(){if(!demo)return;state=beforeDemo;demo=false;$('demoButton').textContent='예시 둘러보기';$('connectionState').textContent='연결 대기';$('syncTime').textContent='위플랩의 룰렛 통계를 연결해 주세요.';}
$('demoButton').onclick=()=>{if(demo){exitDemo();render();return;}beforeDemo=state;state={version:1,active:'demo',lists:{demo:{label:'예시 · 실제 후원 내역이 아닙니다',rows:[{user:'달빛시청자',id:'demo_moon',item:'A 단컷',count:6},{user:'달빛시청자',id:'demo_moon',item:'즉석 방셀',count:2},{user:'구름시청자',id:'demo_cloud',item:'A 단컷',count:3},{user:'구름시청자',id:'demo_cloud',item:'냔생복',count:4},{user:'별빛시청자',id:'demo_star',item:'움짤 B',count:9},{user:'별빛시청자',id:'demo_star',item:'노래',count:1}],done:{},updated:''}}};demo=true;$('connectionState').textContent='예시 모드';$('syncTime').textContent='가상 데이터입니다. 변경 사항은 저장되지 않습니다.';$('demoButton').textContent='예시 닫기';render();};
const params=new URLSearchParams(location.hash.slice(1)),token=params.get('bridge'),source=window.opener;let boundLabel=params.get('list');
if(token&&source&&boundLabel){
  history.replaceState(null,'',location.pathname+location.search);
  let connected=false,received=false;
  const readyTimer=setInterval(()=>{if(connected){clearInterval(readyTimer);return;}source.postMessage({type:'roulette-ready',token},'https://weflab.com');},500);
  setTimeout(()=>{clearInterval(readyTimer);if(!connected){$('connectionState').textContent='연결되지 않음';$('syncTime').textContent='위플랩에서 연결 북마크를 다시 실행해 주세요.';}},30000);
  window.addEventListener('message',e=>{
    if(e.origin!=='https://weflab.com'||e.source!==source||e.data?.type!=='roulette-note'||e.data.token!==token||e.data.label!==boundLabel)return;
    connected=true;lastMessage=Date.now();
    if(e.data.error){$('connectionState').textContent='확인 필요';$('syncTime').textContent=String(e.data.error);$('dot').classList.remove('live');return;}
    try{
      const rows=C.taskRows(e.data.rows);exitDemo();
      const list=makeList(boundLabel,!received);
      const next=C.mergeSnapshot(list,rows);
      if(!received||JSON.stringify(list.rows)!==JSON.stringify(next.rows)){
        Object.assign(list,next);list.updated=new Date().toISOString();save();render();
      }
      received=true;
      $('connectionState').textContent='위플랩 연결됨';$('dot').classList.add('live');
      $('syncTime').textContent=boundLabel+' · 마지막 반영 '+new Date(list.updated).toLocaleTimeString('ko-KR');
    }catch(err){$('connectionState').textContent='확인 필요';$('syncTime').textContent=err.message;$('dot').classList.remove('live');}
  });
}
window.addEventListener('storage',e=>{if(e.key!==STORE||!e.newValue||demo)return;try{state=validateState(JSON.parse(e.newValue));render();}catch{toast('다른 창의 저장 내용을 읽지 못했습니다.');}});
setInterval(()=>{if(lastMessage&&Date.now()-lastMessage>12000){$('dot').classList.remove('live');if(!demo){$('connectionState').textContent='연결 확인 필요';$('syncTime').textContent='위플랩 탭을 확인해 주세요. 저장된 통계는 유지됩니다.';}}},4000);render();



